/**
 * 10 Global Cities Configuration
 * Contains coordinates, currency codes, population, and country flags
 */
const CITIES = [
  {
    id: 'new-york',
    name: 'New York',
    country: 'USA',
    flag: '🇺🇸',
    lat: 40.7128,
    lon: -74.0060,
    currency: { code: 'USD', symbol: '$', name: 'US Dollar' },
    population: 8336817,
    timezone: 'America/New_York',
  },
  {
    id: 'london',
    name: 'London',
    country: 'UK',
    flag: '🇬🇧',
    lat: 51.5074,
    lon: -0.1278,
    currency: { code: 'GBP', symbol: '£', name: 'British Pound' },
    population: 8982000,
    timezone: 'Europe/London',
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    lat: 35.6762,
    lon: 139.6503,
    currency: { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
    population: 13960000,
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    country: 'India',
    flag: '🇮🇳',
    lat: 19.0760,
    lon: 72.8777,
    currency: { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
    population: 20667656,
    timezone: 'Asia/Kolkata',
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    flag: '🇦🇪',
    lat: 25.2048,
    lon: 55.2708,
    currency: { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
    population: 3478300,
    timezone: 'Asia/Dubai',
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    flag: '🇦🇺',
    lat: -33.8688,
    lon: 151.2093,
    currency: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
    population: 5312000,
    timezone: 'Australia/Sydney',
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    flag: '🇫🇷',
    lat: 48.8566,
    lon: 2.3522,
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    population: 2161000,
    timezone: 'Europe/Paris',
  },
  {
    id: 'sao-paulo',
    name: 'São Paulo',
    country: 'Brazil',
    flag: '🇧🇷',
    lat: -23.5505,
    lon: -46.6333,
    currency: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
    population: 12325232,
    timezone: 'America/Sao_Paulo',
  },
  {
    id: 'cairo',
    name: 'Cairo',
    country: 'Egypt',
    flag: '🇪🇬',
    lat: 30.0444,
    lon: 31.2357,
    currency: { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
    population: 10145000,
    timezone: 'Africa/Cairo',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    flag: '🇸🇬',
    lat: 1.3521,
    lon: 103.8198,
    currency: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
    population: 5850342,
    timezone: 'Asia/Singapore',
  },
];

module.exports = CITIES;
